[package]
name = "colorous"
version = "0.0.0" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Professional color schemes ported from d3-scale-chromatic"
repository = "https://github.com/dtolnay/colorous"
documentation = "https://docs.rs/colorous"
readme = "README.md"
keywords = ["color", "scheme", "gradient"]
categories = ["graphics"]

[dev-dependencies]
dejavu = "=2.37.0"
image = "0.23"
imageproc = "0.20"
rusttype = "0.8"

[badges]
travis-ci = { repository = "dtolnay/colorous" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
